### ISSUE TITLE
Move user text commands to slash commands (and maybe add context menu options)

### ISSUE THREAD

**Issue by apschultz** [ClanAODDev/aod-discord-bot#8]
!mute
!unmute
!setptt
!clearptt
!kick
!ban
!addguest (https://github.com/ClanAODDev/aod-discord-bot/issues/5)
!removeguest (https://github.com/ClanAODDev/aod-discord-bot/issues/5)
... others? Need to check

May make sense to isolate these under a single root `/user` or `/member` to keep the top level better organized

**Comment by bashtech** [comment]
Other missing commands:

!tracker
!reminder
!addaod
!remaod
!purge

... and maybe some additional admin/owner only commands.

**Comment by apschultz** [comment]
addaod/remaod can be disregarded
